<script setup>
import "vue-sonner/style.css";
import { Toaster } from "@/components/ui/sonner";

/* ---------------------
   Global SEO defaults
---------------------- */
useSeoMeta({
  titleTemplate: "%s | Massive Barbeque",
  ogSiteName: "Massive Barbeque",
  ogType: "website",
  twitterCard: "summary_large_image",
});

const route = useRoute();
const config = useRuntimeConfig();

/* ---------------------
   Canonical + HTML attrs
   (canonical auto-generated by @nuxtjs/seo from site.url)
---------------------- */
useHead({
  htmlAttrs: { lang: "en" },
  link: [
    {
      rel: "icon",
      type: "image/png",
      href: "/images/Food/Logos/submark.png",
    },
    {
      rel: "apple-touch-icon",
      href: "/images/Food/Logos/submark.png",
    },
  ],
});

/* --------------------------------
   Auth hydration — keep Navbar / guards in sync
   on every full load (e.g. gateway return).
--------------------------------- */
const { fetchSession } = useAuth();
onMounted(() => {
  // Hydrate from the server once per app load; dashboard pages
  // also call this but the dedup via `pending` makes it safe.
  fetchSession();
});

/* --------------------------------
   Google Analytics 4 (Nuxt 4 safe)
--------------------------------- */

onMounted(() => {
  // Strict GA id shape — never inject an attacker-influenced string as code.
  const gaId = String(config.public.gaId || "");
  if (!/^G-[A-Z0-9]{4,}$/.test(gaId)) return;

  // Prevent duplicate injection
  if (window.gtag) return;

  // Load GA library
  const gtagScript = document.createElement("script");
  gtagScript.src = `https://www.googletagmanager.com/gtag/js?id=${gaId}`;
  gtagScript.async = true;
  document.head.appendChild(gtagScript);

  // Init GA
  const inlineScript = document.createElement("script");
  inlineScript.innerHTML = `
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    window.gtag = gtag;
    gtag('js', new Date());
    gtag('config', '${gaId}', {
      send_page_view: false
    });
  `;
  document.head.appendChild(inlineScript);
});

// Track SPA route changes — path only, never fullPath: query strings
// carry order UUIDs (?order=) and other PII that must not reach Google.
watch(
  () => route.path,
  () => {
    if (!window.gtag) return;
    window.gtag("event", "page_view", {
      page_path: route.path,
    });
  },
);
</script>

<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
    <Toaster
      position="bottom-right"
      :duration="4000"
      :rich-colors="true"
      :close-button="true"
      :toast-options="{
        class: 'border-0',
        classes: {
          toast: 'border border-border text-foreground',
          success: 'bg-green-50 border-green-200 text-green-900 dark:bg-green-950 dark:border-green-800 dark:text-green-100',
          error: 'bg-red-50 border-red-200 text-red-900 dark:bg-red-950 dark:border-red-800 dark:text-red-100',
          title: 'text-sm font-medium',
          description: 'text-xs opacity-80',
          actionButton:
            'bg-primary text-primary-foreground hover:opacity-80 text-xs',
          cancelButton: 'text-muted-foreground hover:text-foreground text-xs',
        },
      }"
    />
  </div>
</template>
